baseURL = "https://clemenssiebler.com/"
languageCode = "en-us"
title = "Clemens Siebler's blog about Cloud & AI"
theme = "paper"

[params]
  color = 'light'                 # linen, wheat, gray, light

  # header social icons
  twitter = 'clemenssiebler'
  github = 'csiebler'
  instagram = 'csiebler'
  rss = true

  # home page profile
  avatar = 'clemens.siebler@gmail.com'
  name = 'Clemens Siebler'
  # bio = 'YOUR_BIO'

  # misc
  disableHLJS = false
  monoDarkIcon = false